import {isFunction} from './Function';
import {Infinity, Number, Date} from '@nlib/global';
import {testFunction} from '@nlib/test';

testFunction(isFunction, {input: -Infinity, expected: false});
testFunction(isFunction, {input: Number.MAX_SAFE_INTEGER * -2, expected: false});
testFunction(isFunction, {input: -1.1, expected: false});
testFunction(isFunction, {input: -1, expected: false});
testFunction(isFunction, {input: 0, expected: false});
testFunction(isFunction, {input: 1, expected: false});
testFunction(isFunction, {input: 1.1, expected: false});
testFunction(isFunction, {input: Number.MAX_SAFE_INTEGER * 2, expected: false});
testFunction(isFunction, {input: Infinity, expected: false});
testFunction(isFunction, {input: '', expected: false});
testFunction(isFunction, {input: 'foo', expected: false});
testFunction(isFunction, {input: [], expected: false});
testFunction(isFunction, {input: null, expected: false});
testFunction(isFunction, {input: true, expected: false});
testFunction(isFunction, {input: false, expected: false});
testFunction(isFunction, {input: {}, expected: false});
testFunction(isFunction, {input: new Date(), expected: false});
testFunction(isFunction, {input: new Date('Foo'), expected: false});
testFunction(isFunction, {input: () => null, expected: true});
