import {Infinity, Number, Date} from '@nlib/global';
import {testFunction} from '@nlib/test';
import {isObjectLike} from './ObjectLike';

testFunction(isObjectLike, {expected: false, input: -Infinity});
testFunction(isObjectLike, {expected: false, input: Number.MAX_SAFE_INTEGER * -2});
testFunction(isObjectLike, {expected: false, input: -1.1});
testFunction(isObjectLike, {expected: false, input: -1});
testFunction(isObjectLike, {expected: false, input: 0});
testFunction(isObjectLike, {expected: false, input: 1});
testFunction(isObjectLike, {expected: false, input: 1.1});
testFunction(isObjectLike, {expected: false, input: Number.MAX_SAFE_INTEGER * 2});
testFunction(isObjectLike, {expected: false, input: Infinity});
testFunction(isObjectLike, {expected: false, input: ''});
testFunction(isObjectLike, {expected: false, input: 'foo'});
testFunction(isObjectLike, {expected: true, input: []});
testFunction(isObjectLike, {expected: false, input: null});
testFunction(isObjectLike, {expected: false, input: true});
testFunction(isObjectLike, {expected: false, input: false});
testFunction(isObjectLike, {expected: true, input: {}});
testFunction(isObjectLike, {expected: true, input: new Date()});
testFunction(isObjectLike, {expected: true, input: new Date('Foo')});
testFunction(isObjectLike, {expected: true, input: () => null});
