import {testFunction} from '@nlib/test';
import {isUUID} from './UUID';

testFunction(isUUID, {expected: false, input: -Infinity});
testFunction(isUUID, {expected: false, input: Number.MAX_SAFE_INTEGER * -2});
testFunction(isUUID, {expected: false, input: -1.1});
testFunction(isUUID, {expected: false, input: -1});
testFunction(isUUID, {expected: false, input: 0});
testFunction(isUUID, {expected: false, input: 1});
testFunction(isUUID, {expected: false, input: 1.1});
testFunction(isUUID, {expected: false, input: Number.MAX_SAFE_INTEGER * 2});
testFunction(isUUID, {expected: false, input: Infinity});
testFunction(isUUID, {expected: false, input: ''});
testFunction(isUUID, {expected: false, input: 'foo'});
testFunction(isUUID, {expected: false, input: '12345678-abcd-ef01-1234-00009999000'});
testFunction(isUUID, {expected: true, input: '12345678-abcd-ef01-1234-000099990000'});
testFunction(isUUID, {expected: false, input: []});
testFunction(isUUID, {expected: false, input: null});
testFunction(isUUID, {expected: false, input: true});
testFunction(isUUID, {expected: false, input: false});
testFunction(isUUID, {expected: false, input: {}});
testFunction(isUUID, {expected: false, input: new Date()});
testFunction(isUUID, {expected: false, input: new Date('Foo')});
testFunction(isUUID, {expected: false, input: () => null});
testFunction(isUUID, {expected: false, input: undefined});
