import {testFunction} from '@nlib/test';
import {isValidDate} from './ValidDate';

testFunction(isValidDate, {expected: false, input: -Infinity});
testFunction(isValidDate, {expected: false, input: Number.MAX_SAFE_INTEGER * -2});
testFunction(isValidDate, {expected: false, input: -1.1});
testFunction(isValidDate, {expected: false, input: -1});
testFunction(isValidDate, {expected: false, input: 0});
testFunction(isValidDate, {expected: false, input: 1});
testFunction(isValidDate, {expected: false, input: 1.1});
testFunction(isValidDate, {expected: false, input: Number.MAX_SAFE_INTEGER * 2});
testFunction(isValidDate, {expected: false, input: Infinity});
testFunction(isValidDate, {expected: false, input: ''});
testFunction(isValidDate, {expected: false, input: 'foo'});
testFunction(isValidDate, {expected: false, input: []});
testFunction(isValidDate, {expected: false, input: null});
testFunction(isValidDate, {expected: false, input: true});
testFunction(isValidDate, {expected: false, input: false});
testFunction(isValidDate, {expected: false, input: {}});
testFunction(isValidDate, {expected: true, input: new Date()});
testFunction(isValidDate, {expected: false, input: new Date('Foo')});
